### ISSUE TITLE
No signature of method: compileSass()

### ISSUE THREAD

**Issue by darkomenx** [EtienneMiret/sass-gradle-plugin#10]
I installed your Gradle plugin like that : 

```
plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.0.9'
    id 'io.miret.etienne.sass' version '1.1.1'
}

sass {
    version = '1.24.4'
    directory = file ("${rootDir}/.gradle/sass")
    baseUrl = 'https://github.com/sass/dart-sass/releases/download'
}

compileSass {
    outputDir = project.file ("${buildDir}/sass")
    sourceDir = project.file (${projectDir}/src/main/sass)

    loadPath project.file ('sass-lib')
    loadPath project.file ('/var/lib/compass')

    style = expanded

    noCharset ()
    noErrorCss ()
    watch ()

    sourceMap = file
    sourceMapUrls = relative
}
```

But now when I want to launch anything gradle task, I have this error : 

`> No signature of method: build_dykzla3ri5dkhpuy7mfct10yx.compileSass() is applicable for argument types: (build_dykzla3ri5dkhpuy7mfct10yx$_run_closure4) values: [build_dykzla3ri5dkhpuy7mfct10yx$_run_closure4@4a7da083]`

What do you think about that ?

is there others requirements or prerequisites to use your plugin ?

Thank you for your help

**Comment by EtienneMiret** [comment]
Hello @darkomenx!

There is a typo in your `build.gradle`:

```groovy
sourceDir = project.file (${projectDir}/src/main/sass)
```

should be written as:

```groovy
sourceDir = project.file ("${projectDir}/src/main/sass")
```

Since there is the same typo in the documentation, I will update it.
