### ISSUE TITLE
Issue with running plugin, gradle configuration error?

### ISSUE THREAD

**Issue by ingeniotechnologies** [EtienneMiret/sass-gradle-plugin#11]
Hi @EtienneMiret, 

I'm a gradle novice and I'm currently attempting to have my scss files converted to css upon saving changes, just as I had it using a run configuration in eclipse.

I'm currently using netbeans v12.4 on a gradle web project. I originally thought that it could be automatically done by the IDE, since the css preprocessor settings (e.g. path to sass executable and input and output properties) ARE available on the IDE, but no "run configurations". Maybe the settings are there so that a sass compiler plugin can pick them up or something.

So I guess the only route to have this working is by installing an sass compiler plugin.

So I configured my build.gradle file to as follows:

```
plugins {
    id 'java'
    id 'jacoco'
    id 'war'
    id 'io.miret.etienne.sass' version '1.1.1'
}

```
and then pasted your configuration example (just changed my paths) as follows:

```
compileSass {
  // Directory where to output generated CSS:
  outputDir = project.file ("${projectDir}/src/main/webapp/resources/layout/css")

  // Source directory containing sass to compile:
  sourceDir = project.file ("${projectDir}/src/main/webapp/resources/layout/sass")

  // Adds a directory to sass load path (default is empty):
  loadPath project.file ('sass-lib')
  loadPath project.file ('/var/lib/compass')

  // Set the output style:
  // Possible values are “expanded” and “compressed”, default is “expanded”.
  style = expanded

  // Don’t emit a @charset for CSS with non-ASCII chars (default to emit):
  noCharset ()

  // When an error occurs, do not emit a stylesheet describing it:
  // (Default to emit)
  noErrorCss ()

  // Watch sass files in sourceDir for changes
  watch ()

  // Source map style:
  //  - file: output source map in a separate file (default)
  //  - embed: embed source map in CSS
  //  - none: do not emit source map.
  sourceMap = file

  // How to link source maps to source files [relative (default) or absolute]:
  sourceMapUrls = relative
}

```
I then run the `compileSass` task directly from the netbeans IDE (Project->Run Gradle->Tasks...) and get following message after a few seconds:

`Sass is watching for changes. Press Ctrl-C to stop.`

I then went to change a file and after saving it, the `Build (Project Web Store) Task :compileSass` progress bar at the bottom right started to flash by, but wouldn't stop after a long while. I could not stop the tasks by hitting the stop button. So after a while, I closed out netbeans.

Now, when I go back into netbeans and start the task `compileSass`, the progress bar endlessly cycles without stopping. It seems like something got stock there from the first action after I forcefully exited the IDE and after restaring netbeans and the `compileSass `task, it picks up where it left off.

What do you think? Do you think you can point me in the right direction. I would appreciate it very much!

Best regards,

**Comment by EtienneMiret** [comment]
Hi!

The issue might be here:

```
// Adds a directory to sass load path (default is empty):
loadPath project.file ('sass-lib')
loadPath project.file ('/var/lib/compass')
```

Those are meant to add sass libraries to the load path. If you aren’t using any library, you shouldn’t add anything. And if you do are using a sass library, make sure to point to its correct location. It seems `dart-sass` will fail if directories on its load path do not exist.

**Comment by ingeniotechnologies** [comment]
Thanks, I've commented those two lines out, but when I run task `compileSass`, the progress bar starts cycling non-stop. Is this supposed to happen, since it's monitoring the specified file folders?

Best Regards!

**Comment by EtienneMiret** [comment]
Hi @eframsergio!

I’m not sure what the NetBeans UI should display, but yes, with the `watch ()` option you’ve enabled, the task watches for changes in the source folder and will recompile whenever they change. The default behavior, without that option, is just to compile files from source to destination folder once, and then terminate.

As a side note, while this should work, I wouldn’t recommend having build outputs under the `src` folder. Files under this folder are supposed to be under version control, and the CSS output of the SASS compilation, well, isn’t. Also, the `war` task *may* pickup files under the `src/main/webapp` directory *before* the `compileSass` task is ran.

Without any option set, my plugin will compile any sass file under `src/main/sass` to a directory in the build folder (`build/sass`) and configure the `war` task to pickup files there and put them at the root of the generated war. If you want the CSS to be available under `resources/layout/css` in the web app, I recommend you to use the plugin defaults and move your sass files to `src/main/sass/resources/layout/css`.

**Comment by ingeniotechnologies** [comment]
Hi @EtienneMiret,

Thank you very much for your prompt responses. I still wasn't able to make it work at this moment.

Nothing seems to happen, even when I move sass folder in default expected location.

I will try to get back to it soon.

Thanks!

**Comment by EtienneMiret** [comment]
Hi @eframsergio,

I’m sorry to ear you’re still struggling. Maybe have a look at the samples and just uploaded in PR #12 and please let me know if they help you or you still have some questions.

**Comment by ingeniotechnologies** [comment]
Very cool, will do! Thanks!

**Comment by ingeniotechnologies** [comment]
Ok, I followed instructions as described in simple example.

All I did was to copy my sass files to `CultivarteWebStore\src\main\sass` - all files under that folder are prefixed with an "_" and with an *.scss extension.

I then added:

`id 'io.miret.etienne.sass' version '1.1.2'`

to `plugins {...` section 

This is the output: when I run `compileSass` from NetBeans:

```
cd C:\...\Development\NetBeansProjects\CultivarteWebStore; .\gradlew.bat --configure-on-demand -x check compileSass
Configuration on demand is an incubating feature.
> Task :downloadSass UP-TO-DATE
> Task :installSass
> Task :compileSass

BUILD SUCCESSFUL in 935ms
3 actionable tasks: 2 executed, 1 up-to-date
```

The only thing that appears to happen is that an empty `sass` folder is created under `CultivarteWebStore\build`, but  nothing seems to compile. Expecting to see generated *.css files...

What do you think? Maybe the way I'm prefixing my file names?

**Comment by ingeniotechnologies** [comment]
Ha, I just removed the "_" from one of my files, and its css output DID end up in the build/sass folder!

**Comment by ingeniotechnologies** [comment]
By the way, I think this is the correct behavior. 

All my scss files (_utils.scss, _variables.scss, _mixins.scss, _main.scss, _product.scss, etc) have an underscore prefix. I can then just have a file called layout.scss that imports all the individual scss files with the underscore prefix. This way, the compiler only sees the file named layout.scss and it works out perfectly.

Your plugin is pretty awesome, thanks a lot for all the help!

Best regards!

**Comment by EtienneMiret** [comment]
You’re welcome!

**Comment by ingeniotechnologies** [comment]
As a side note, when the plugin is run with the `watch()` option; the IDE displays the progress bar running nonstop at the bottom taskbar. And it stays this way the whole entire time while eclipse is open.

Since the plugin left the gradle daemon running in the background; it makes sense that it indicates that the plugin continues working (albeit, in the background).

I've used mostly eclipse in the past, and a nonstop progress bar usually indicates that eclipse would get stuck during a validation for example, so I would have to shutdown eclipse in order to get it unstuck.

When it happens in NetBeans after running your plugin with the `watch()` option, it's a bit unsettling because it appears that the IDE got stuck, just as eclipse did. I need the progress bar to visually indicate if an action is happening at any point and then have it stop after is done.

What I now do in order to counteract this behavior is to shut down NetBeans and then get back in. Since the gradle daemon continues running, my scss files continue to compile after getting saved, but without the progress bar running nonstop.

But, top notch plugin. Thanks again!
