### ISSUE TITLE
Disable automatic copying of CSS files to WAR file

### ISSUE THREAD

**Issue by bwolff** [EtienneMiret/sass-gradle-plugin#17]
Thanks for providing this useful plugin!

Feature: It would be nice to have a configuration switch to disable the automatic copying of the compiled CSS files to the WAR file when the WAR plugin is present. It could be an additional switch like "disableCopyToWar()".

Context: I'm using this plugin in a Spring Boot application and use it to compile SCSS files from "src/main/sass" to a subfolder of "src/main/resources/". This is an intermediate step and the CSS files from there will then already be packaged in the WAR file according to the default resource processing of the WAR plugin. So in my use-case, the SASS plugin copies all files of the output folder in the root of the WAR file, which requires an additional build step to remove these files again. Having a possibility to disable that behaviour in the plugin would be nice and would improve the support for more custom setups such as mine.

Cheers,
Ben

**Comment by EtienneMiret** [comment]
Hello Ben!

I can (and will) provide an option to disable the automatic copy to war. However, why do you want the compiled CSS to be put in `src/main/resources`? In my humble opinion, the `src` folder and all its subfolders should only contain sources that are under version control, not generated code.

You mentioned you were putting the generated CSS in a subfolder of `src/main/resources`. In case your only need is to put the CSS files inside a subfolder of the WAR rather than the root, there is already an option for this, introduced in release [1.2.0]:

```
compileSass {
  // Sub path where to copy generated CSS, eg relative to war root:
  destPath = "."
}
```

[1.2.0]: https://github.com/EtienneMiret/sass-gradle-plugin/releases/tag/1.2.0

**Comment by bwolff** [comment]
Salut Étienne,

in a Spring Boot application, [it is often a convention to place static web resources](https://www.baeldung.com/spring-mvc-static-resources) in a folder like `src/main/resources/static`. From there they will be automatically packaged in the WAR file and then served with proper caching headers at runtime. Spring Boot uses the Java and WAR plugins, so the `processResources` task already copies them to the proper location in the WAR file. Having the `processResources` task depend on the `compileSass` of your plugin integrates it seamlessly and with mechanimus, also with minimal configuration.

In my case I'm also using an older server-side UI technology ([RAP/RWT](https://www.eclipse.org/rap/)) that uses CSS to style the UI components. These CSS files need to be on the classpath, but mustn't be served to the browser. So I'm placing theses files in `src/main/resources/themes`. These are the CSS files I'm generating thanks to your nice plugin. Again, these files are automatically bundled using the `processResources` task.

However, your remark is perfectly valid. I should not put generated resources in the `src/main/resources` folder. Instead, I will restructure this to have it instead outputted to e.g. `generated/main/resources`, which will then be added to the main classpath so that the resources in it will the copied and processed like the main resource folder.

Cheers,
Ben

**Comment by EtienneMiret** [comment]
Done in release 1.3.0 that was just published.

The switch is `noAutoCopy ()` and must be put in the `sass` closure.

**Comment by bwolff** [comment]
I tested it and it works. Thanks a lot for implementing this feature!!
