### ISSUE TITLE
Handle arm64 architectures

### ISSUE THREAD

**Issue by perlow** [EtienneMiret/sass-gradle-plugin#21]
Recent versions of dart-sass support both linux and apple arm64 architectures. This is fixed by https://github.com/EtienneMiret/sass-gradle-plugin/pull/20.

**Comment by EtienneMiret** [comment]
Thank-you very much for your PR. It has been merged and a new 1.4.0 release was publish with this change.

**Comment by perlow** [comment]
Thanks!
