### ISSUE TITLE
sourceDir is not accessible when using Kotlin Script

### ISSUE THREAD

**Issue by ftomassetti** [EtienneMiret/sass-gradle-plugin#29]
```
tasks.named<CompileSass>("CompileSass") {
    loadPath(project.file("${projectDir}/src/main/resources/coderdocs/assets/scss"))
    sourceDir.set(sassSources)
    outputDir = project.file("${projectDir}/src/main/resources/coderdocs-dist/assets/css")
}
```

>   Line 119:     sourceDir.set(sassSources)
                ^ Cannot access 'sourceDir': it is private in 'CompileSass'

**Comment by EtienneMiret** [comment]
There is a setter available:

```kotlin
tasks.named<CompileSass>("compileSass") {
  setSourceDir(project.file("src/main/style"))
}
```

I will add a getter though, because of this [Kotlin caveat](https://kotlinlang.org/docs/java-interop.html#70ab475d):

> Note that, if the Java class only has a setter, it isn't visible as a property in Kotlin because Kotlin doesn't support set-only properties.
