### ISSUE TITLE
Setting version does not work

### ISSUE THREAD

**Issue by mnlipp** [EtienneMiret/sass-gradle-plugin#7]
Setting a version like
```gradle
sass {
    // dart-sass version to use:
    version = '1.26.2'
}
```
Results in a failed download attempt:
```
Not Found (HTTP status code: 404, URL: https://github.com/sass/dart-sass/releases/download/1.26.2/dart-sass-1.24.4-linux-x64.tar.gz)
```

The URL uses the specified version for the directory but not for the file name. (Most likely, the file name is evaluated in the wrong gradle phase.)

**Comment by EtienneMiret** [comment]
Hi @mnlipp. Thank-you for reporting this issue. I was able to reproduce it in a functional test, so it should be fixed soon.
